// automatically generated by the FlatBuffers compiler, do not modify

package net.openhft.chronicle.logger.entry;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EntryTimestamp extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EntryTimestamp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long epochSecond() { return bb.getLong(bb_pos + 0); }
  public void mutateEpochSecond(long epoch_second) { bb.putLong(bb_pos + 0, epoch_second); }
  public int nanoAdjust() { return bb.getInt(bb_pos + 8); }
  public void mutateNanoAdjust(int nano_adjust) { bb.putInt(bb_pos + 8, nano_adjust); }

  public static int createEntryTimestamp(FlatBufferBuilder builder, long epochSecond, int nanoAdjust) {
    builder.prep(8, 16);
    builder.pad(4);
    builder.putInt(nanoAdjust);
    builder.putLong(epochSecond);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EntryTimestamp get(int j) { return get(new EntryTimestamp(), j); }
    public EntryTimestamp get(EntryTimestamp obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

